language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - cd app
  - npm install
script:
  - npm run test
  - npm run build
git:
  depth: false
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  on: master
  site: hitch-inspection-tool
  skip_cleanup: true
  verbose: true
